Algoritmo "5_NUMPARES"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Wheslley Rimar 
// Descrição   : Numeros Pares até 100
// Autor(a)    :Renan Correa
// Data atual  : 11/08/2020
Var
// Seção de Declarações das variáveis 
      n1:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       n1<-0
       Escreval(n1)

       Enquanto (n1<100) faca
       n1<-n1+2
       Escreval(n1)
       fimenquanto

Fimalgoritmo